export interface KpiPostbagBccp {
  fromposcode: number;
  toposcode: number;
  mailtripnumber: number;
  mailtripdate: number;
  postbagindex: number;
  e2date: number;
  totalitem: number;
  totalweight: number;
  totalweightconver: number;
  workcenter: number;
  workdate: number;
  workshift: number;
  tracepostbagdate: string | Date;
  postbagcode: string;
  isleft: number;
  bc37code: string;
  bc37fromposcode: number;
  bc37toposcode: number;
  bc37date: number;
  bc37index: number;
  leavetime: string | Date;
  e2time: number;
  idvnpost: number;
  id_mailroute: number;
  id_cutoff: number;
  bc37createtime: string | Date;
  accepttime: string | Date;
  acceptdate: number;
  iskpi: number;
  isxnd: number;
  postbagtypecode: string;
  transportcode: string;
  carleavetime: string | Date;
  realleavetime: string | Date;
  issync: number;
  adjusted: number;
  reason: string;
  tracetime: string | Date;
  status2get: number;
  caseweight: number;
  mailtriptype: number;
}