export interface E2I2 {
  mabc: number;
  chthu: number;
  tuiso: number;
  tongso: number;
  khoiluong: number;
  cuoccs: number;
  cuocdv: number;
  ngay: number;
  gio: number;
  manv: number;
  mabc_kt: number;
  dagui: number;
  date_log: string | Date;
  trlg_tui: number;
  tui_f: number;
  dong: string;
  mo: string;
  rong: number;
  loai: number;
  congphat: number;
  tren: number;
  kltren: number;
  cptren: number;
  ngaykt: number;
  cakt: number;
  khoa: number;
  chk: number;
  di_ngoai: number;
  klg_quidoi: number;
  tongkhoiluong: number;
  id_e2: string;
  loai_tui: number;
  ma_day_thit: number;
  dvu: number;
  lephi: number;
  mac_address: string;
  local_ip: string;
  computer_name: string;
  loai_ht: number;
  lastupdatetime: string | Date;
  isbackup: number;
  loai_vo_tui: number;
}